var data = [ {"id": 1,
"category":"React",
"name":"Modern React with Redux [2020 Update]",
"description": "React is the most popular Javascript library of the last five years, and the job market is still hotter than ever.  Companies large and small can't hire engineers who understand React and Redux fast enough, and salaries for engineers are at an all time high.  It's a great time to learn React!",
"img":"https://www.freecodecamp.org/news/content/images/2020/02/Ekran-Resmi-2019-11-18-18.08.13.png",
"price":289.99},
{"id": 2,
"category":"MySQL",
"name":"The Complete SQL Bootcamp 2020: Go from Zero to Hero",
"description": "You'll learn how to read and write complex queries to a database using one of the most in demand skills - PostgreSQL. These skills are also applicable to any other major SQL database, such as MySQL, Microsoft SQL Server, Amazon Redshift, Oracle, and much more.",
"img":"https://logos-download.com/wp-content/uploads/2016/05/MySQL_logo_logotype.png",
"price":199.99},
{"id":3,
"category":"Learn API",
"name":"API and Web Service Introduction",
"description":"Learn all about APIs and RESTful Web Services the easy way!  This includes the BIG PICTURE, with ALL the main components of APIs.  Topics covered include: API (of course), Web Service, JSON, XML, HTTP, REST, SOAP, OAuth, OpenID Connect, and examples in Postman and Python. AND we have plenty of exercises so you can solidify what you've learned!",
"img":"https://www.akamai.com/uk/en/multimedia/images/video/akamai-api-video-thumbnail.jpg?imwidth=1366",
"price":399.99},
{"id":4,
"category":"Learn Node.js",
"name":"The Complete Node.js Developer Course",
"description":"NodeJS is a rapidly growing web server technology, and Node developers are among the highest paid in the industry. Knowing NodeJS well will get you a job or improve your current one by enabling you to build high quality, robust web applications.",
"img":"https://railsware.com/blog/wp-content/uploads/2018/09/2400%D1%851260-rw-blog-node-js.png",
"price":229.99},
{"id":5,
"category":"Learn MS Excel",
"name":"Microsoft Excel - Advanced Excel Formulas & Functions",
"description": "Learn how to THINK like Excel, and write powerful and dynamic Excel formulas from scratch",
"img":"https://www.itsolutions-inc.com/assets/uploads/news/ms-excel-logo.png",
"price":39.99},
{"id":6,
"category":"Learn MS Word",
"name":"Master Microsoft Word Beginner to Advanced",
"description": "Brand New Over-The-Shoulder Video Series On How To Write Better & Faster Using MS Word.",
"img":"https://media.proprofs.com/images/QM/user_images/2236918/1520729095.jpg",
"price":29.99},
{"id":7,
"category":"Cloud Computing",
"name":"Introduction to Cloud Computing on Amazon AWS for Beginners",
"description": "With technological advancements, cloud computing is becoming standard and mainstream in IT world. Companies of all sizes are looking to transform existing traditional IT services to",
"img":"https://networkencyclopedia.com/wp-content/uploads/2019/09/cloud-computing.png",
"price":39.99},
{"id":8,
"category":"Learn Front-End Web Development",
"name":"The Complete Front-End Web Development Course!",
"description": "If you would like to get started as a front-end web developer, you are going to LOVE this course! Work on projects ranging from a simple HTML page to a complete JavaScript based Google Chrome extension.",
"img":"https://s3-ap-south-1.amazonaws.com/eww-wp/wp-content/uploads/2019/08/07133751/frontend-web-development.jpg",
"price":399.99},
{"id":9,
"category":"Full-Stack Web Development",
"name":"Full-Stack Web Development For Beginners",
"description": "Build a chat application from scratch with backend web development skills: Node and express",
"img":"https://www.acewebacademy.com/blog/wp-content/uploads/2017/08/What-is-Full-Stack-Development-Definition-672x372.jpg",
"price":499.99},
{"id":10,
"category":"Learn SEO",
"name":"SEO 2020: Complete SEO Training + SEO for WordPress Websites",
"description": "This course, SEO 2020 Training: The Complete SEO Course for WordPress Websites is all about 50 SEO (Search Engine Optimization) factors on how to reach top spot on Google search with Search Engine Optimization.",
"img":"https://www.hostpapa.be/blog/wp-content/uploads/2019/07/seo-for-beginners.jpg",
"price":299.99},
{"id":11,
"category":"Adobe",
"name":"Adobe Photoshop Mega Course-From Beginner to Super Designer",
"description":  "This course will allow you to use Photoshop professionally. You will be able to add Photoshop to your CV & start getting paid for your Photoshop skills.",
"img":"https://martechtoday.com/wp-content/uploads/2018/08/adobe-1920-x-1080_v3bvjo-1.png",
"price":39.99},
{"id":12,
"category":"Learn PPC Marketing",
"name":"Social Media Marketing MASTERY | Learn Ads on 10+ Platforms",
"description": "Welcome to the latest and very easy to apply Google AdWords Techniques & Training, designed to take you by the hand and walk you through the process of getting the most out of Google AdWords to propel your business towards success.",
"img":"https://digitaladsonline.com/wp-content/uploads/2017/06/Pay-Per-Click-marketing.png",
"price":189.99},
{"id":13,
"category":"Google add training",
"name":"Ultimate Google Ads Training 2020: Profit with Pay Per Click",
"description": "Get an industry-recognised marketing certification from Google",
"img":"https://static.dribbble.com/users/5321076/screenshots/13932866/media/b0089e0063aa3198f21bcf3fab4fe2ae.jpg",
"price":179.99},
{"id":14,
"category":"Learn python",
"name":"Learn Python Programming Masterclass",
"description": "Have a fundamental understanding of the Python programming language.",
"img":"https://hackr.io/blog/best-way-to-learn-python/thumbnail/large",
"price":189.99},
{"id":15,
"category":"Learn Java",
"name":"Java Programming Masterclass for Software Developers",
"description": "Be able to demonstrate your understanding of Java to future employers.",
"img":"https://technofaq.org/wp-content/uploads/2017/05/learning-java-programming.png",
"price":399.99}]

export default data;